# Generated by Django 3.1.7 on 2021-04-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210401_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='icon',
            field=models.CharField(default='/static/oppo.jpg', max_length=10000),
        ),
    ]
