# Generated by Django 3.1.7 on 2021-04-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_mobile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='rating',
            field=models.IntegerField(default=8, max_length=220),
        ),
    ]
