# Generated by Django 3.1.7 on 2021-04-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_mobile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='rating',
        ),
    ]
