# Generated by Django 3.1.7 on 2021-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_mobile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=199)),
                ('Price', models.CharField(max_length=199)),
                ('Brand', models.CharField(max_length=199)),
                ('Description', models.CharField(max_length=199)),
                ('Origin', models.CharField(max_length=199)),
                ('icon', models.CharField(default='/static/', max_length=199)),
                ('img1', models.CharField(max_length=199)),
                ('img2', models.CharField(max_length=199)),
                ('img3', models.CharField(max_length=199)),
                ('youtube', models.CharField(max_length=199)),
            ],
        ),
    ]
