# Generated by Django 3.1.7 on 2021-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_gadgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='Description',
            field=models.CharField(max_length=19999),
        ),
    ]
